### ISSUE TITLE
code gallery is offline

### ISSUE THREAD

**Issue by gassmoeller** [dealii/website#7]
https://www.dealii.org/code-gallery.html is not reachable. Is it available under a new address?

**Comment by gassmoeller** [comment]
I guess https://dealii.org/developer/doxygen/deal.II/CodeGallery.html is available. Is that the correct place to link to?

**Comment by tamiko** [comment]
@gassmoeller We forgot to convert https://old.dealii.org/code-gallery.html

**Comment by tjhei** [comment]
Yeah. But maybe some of these instructions should be in the readme in the code gallery repo instead?

**Comment by jpthiele** [comment]
> Yeah. But maybe some of these instructions should be in the readme in the code gallery repo instead?

Did a PR for that: https://github.com/dealii/code-gallery/pull/201

**Comment by tamiko** [comment]
@gassmoeller I have put a redirect in place.
